# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Yixuan Zhang
title: Ph.D student at the Ohio State University
email: zhang.7388 [at] osu.edu

darkmode: false

# Social links
github_username:  YIXUANZ
instagram_username: yixzzzzzz
linkedin_username: yixuan-zhang-88a36680

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: img/IMG_0341.png
about_content: | # this will include new lines to allow paragraphs
  I'm a Ph.D student major in computer science and engineering at the Ohio State University. I'm fortunate to work with
  Professor [Deliang Wang](http://www.cse.ohio-state.edu/~dwang/) in in [Perception and Neurodynamics Laboratory](http://web.cse.ohio-state.edu/pnl/). 
  I received my bachelor degree from Southeast University and master degree from Carnegie Mellon University.
  
  I'm interested in music separation and multi-pitch tracking, digital signal processing and deep learning.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Research Experience #(Use this to override about experience section title)
# Master thesis - Design of Matching Criteria for Audio-Based Polyphonic Score-following Systems Using Harmonic Product Spectrum


# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title:  #(Use this to override about more section title)
# more_content: | # this will include new lines to allow paragraphs
#  This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
